### PR TITLE
Update unitTestingJwtPizzaService.md

### PR DESCRIPTION
**Pull request by Jtrom314**
Added a type of `enum` to Role.Admin (only way for me to get the add menu item test to work) and changed the relative path to `database.js` based on the location of the testing file to be correct

### CODE REVIEW

**Comment by Jtrom314** [comment]
const { Role, DB }  = require('../database/database.js');
instead of 
const { DB }  = require('../database/database.js');

**Review by leesjensen — COMMENTED** [review]
This seems a bit strange. I'm guessing the path is dependent on where you put your test. As for the `Admin` enum. That is already defined in `model/models.js`. I believe including that would be the right approach.

**Comment by Jtrom314** [comment]
Yeah that's the case. 

> Now that you have set up jwt-pizza-service to be tested with Jest, you can make sure it is all working right by writing a simple test. Create a file named `authRouter.test.js` in the `src/routes` directory and place the following `hello world` test in file.

I put all of my tests in that file and from what the instructions have it I think most students will have their tests in that file as well. The ../database/database.js is the path needed for that file in particular.

As for the { Role }, I agree that it would be best to import it from model/models.js.

**Comment by leesjensen** [comment]
@Jtrom314  if you can make the 

```js
const { Role, DB } = require('../database/database.js');
```

change to your request I will push it. The path change is fine the way you have it. I just have my test helper is a more generic place then in the routes dir. But your way is probably what others will do.

**Comment by leesjensen** [comment]
@Jtrom314 - This has been around for a while. What did you think of my last comment?

**Comment by Jtrom314** [comment]
Sorry. I must of spaced it. I'll get on that

**Comment by Jtrom314** [comment]
@leesjensen I've updated the file to add in the `Role` object to the import and removed my object work around

**Review by leesjensen — APPROVED** [review]
Thanks!

**Pull request merged**
